# Generated by Django 4.0.3 on 2022-03-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_block_user_alter_wrongpass_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='count_of_wrong_pass',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='wrongpass',
            name='state',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
