# Generated by Django 4.0.3 on 2022-03-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_block_count_of_wrong_pass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrongpass',
            name='state',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
