# Generated by Django 4.0.3 on 2022-03-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_alter_wrongpass_is_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrongpass',
            name='is_locked',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wrongpass',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
