# Generated by Django 4.0.3 on 2022-03-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_remove_wrongpass_is_locked_customuser_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='count_same_id_wp',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
