# Generated by Django 4.0.3 on 2022-03-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_ip_remove_block_count_same_id_wp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
