# Generated by Django 4.0.3 on 2022-03-27 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_ip_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrongpass',
            name='user_IP',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.ip'),
        ),
    ]
