# Generated by Django 4.0.3 on 2022-03-27 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_alter_wrongpass_user_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wrongpass',
            name='user_IP',
        ),
    ]
