# Generated by Django 4.0.3 on 2022-03-27 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_remove_wrongpass_user_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='count_faild_login',
        ),
        migrations.AddField(
            model_name='ip',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wrongpass',
            name='ip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.ip'),
        ),
        migrations.AlterField(
            model_name='ip',
            name='ip',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
