# Generated by Django 4.0.3 on 2022-03-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_remove_ip_count_faild_login_ip_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='username',
        ),
    ]
