# Generated by Django 4.0.3 on 2022-03-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_unblockcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='unblockcode',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
